import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./session-provider";
const outfit = Outfit({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Foreman",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}><SessionWrapper>{children}</SessionWrapper></body>
    </html>
  );
}